version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=mydatabase
      - MONGO_COLLECTION=mycollection
      - GOPHISH_API_URL=http://your-gophish-api-url
      - GOPHISH_API_KEY=your-api-key
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
