version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=mydatabase
      - MONGO_COLLECTION=mycollection
      - GOPHISH_API_URL=http://192.168.1.100:3333
      - GOPHISH_API_KEY=7cd9c0a8c6c7e9f1e4b3a2d1c6b5a4d3
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: gunicorn --bind 0.0.0.0:5000 app:app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
